version: "3.8"

services:
  web:
    build: ./
    container_name: moneygun_container
    working_dir: /moneygun
    command: ./commands/start_server_${MODE}.sh
    volumes:
      - ./commands:/moneygun/commands
      - ./main:/moneygun/main
      - ./money_gun:/moneygun/money_gun
      - ./templates:/moneygun/templates
      - ./manage.py:/moneygun/manage.py
      - ./requirements.txt:/moneygun/requirements.txt
      - static_content:/moneygun/static
      - media_content:/moneygun/media
    ports:
      - "${PORT}:${WSGI_PORT}"
    env_file:
      - .env
    depends_on:
      - postgres


  nginx:
    image: nginx:1.19
    volumes:
      - static_content:/moneygun/static
      - media_content:/moneygun/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    depends_on:
      - web


  postgres:
    image: postgres:14.5
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env


  redis:
    image: redis
    restart: always
    env_file:
      .env


  celery:
    build: ./
    command: ./commands/start_celery.sh
    restart: always
    volumes:
      - ./commands:/moneygun/commands
      - ./main:/moneygun/main
      - ./money_gun:/moneygun/money_gun
      - ./templates:/moneygun/templates
      - ./manage.py:/moneygun/manage.py
      - ./requirements.txt:/moneygun/requirements.txt
    env_file:
      - .env
    depends_on:
      - redis


  celerybeat:
    build: ./
    container_name: celerybeat
    command: ./commands/start_celerybeat.sh
    restart: always
    volumes:
      - ./commands:/moneygun/commands
      - ./main:/moneygun/main
      - ./money_gun:/moneygun/money_gun
      - ./templates:/moneygun/templates
      - ./manage.py:/moneygun/manage.py
      - ./requirements.txt:/moneygun/requirements.txt
    env_file:
      - .env
    depends_on:
      - redis
      - celery


volumes:
  pg_data: { }
  static_content: { }
  media_content: { }
